### ISSUE TITLE
Doesn't compile

### ISSUE THREAD

**Issue by sezeryalcin** [iotpipe/esp8266-dht22#2]
This thing even doesn't compile on Arduino ESP8266 SDK. It has bare compile errors.

So maybe title this as Adafruid Huzzah-dht22 thing.

**Comment by iotpipe** [comment]
It isn't meant to compile on the Arduino ESP8266 SDK.

It is meant to use the manufacturers C SDK.

If you need to use the Arduino SDK then use the adafruit library found here

https://github.com/adafruit/DHT-sensor-library
