### ISSUE TITLE
BUG in read(): 'ets_delay_us' was not declared in this scope

### ISSUE THREAD

**Issue by Anton-V-K** [iotpipe/esp8266-dht22#5]
The error is detected when compiling `dht22.c` with Arduino IDE 1.6.13 for ESP8266 (WeMos D1 R2 & mini):
```
sketch\dht22.c: In function 'bool read()':

dht22.c:80: error: 'ets_delay_us' was not declared in this scope

  os_delay_us(250*1000);

                      ^
```

**Comment by iotpipe** [comment]
Hey Anton,

This library is meanted to be compiled against the manufacturers C SDK, not the Arduino for ESP8266 library.
